from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(response):
	return HttpResponse("<body style='font-family:sans-serif; margin-left: 20%; margin-right:20%; margin-top: 30px; background-color:#bfe7ff;'><h1 style='text-align:center; color:blue;'>Welcome to my website!</h1><div style='background-color:white; padding:60px;'><p>This website is built with framwork django.</p><h3>How I Installed the framework: </h3><p>I installed this framework by using python. I created my own virtual test environment by going on terminal and entering in python3 -m venv mysite. Then after it is created, I activated the environment by typing in source mysite/bin/activate. Now that the environment is activated, I could download Django. The command line to download Django is pip3 install django. Once the installation is finished, I created a django project by typing in django-admin startproject mywebsite. After that, I made an app called main by typing python manage.py startapp main. Then in the main folder, I went to a file called views.py. I added a HttpRequest so the code can show up on the website. I did this by typing from django.http import HttpResponse. Later, I made a function to return the HttpResponse called def index(response). Then I made a urls.py file so I can define the path to my webpage. I added a path such as path('', views.index, name='index'), into the urlpatterns so the user can reach to the website. Next, I modified the settings.py file and added the app that I used. I entered main.apps.MainConfig. Lastly, I went back to terminal and ran the server to execute my website by typing in python manage.py runserver into the terminal command line.</p><h3>Difficulty: </h3><p>This was very difficult to implement at first because I had to use the command line to download the framework and then making a virtual test environment. Some commands that I found online did not work on my laptop so I had to research other commands that would work. I realized that since I have python 3, I should use pip3 command instead of pip. That fixed the issue. Another difficulty I faced was learning how to use the framework itself. I'm not familiar with Django and the syntax are very different than what I have used previously. I fixed this problem by watching more tutorials to understand the syntax and I also got to learn why django is popular. It is popular because it has the ability to make rapid application development.</p></div><footer style='position:absolute; bottom:0; text-align:center; left:0; right:0; padding: 20px;'>Bulit by Helen Tran</footer></body>")



